language: php

sudo: false

php:
    - 5.6

services:
    - mysql

before_script:
    - mysql -e 'create database yii2_basic_tests;'

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - cd tests && php ../vendor/bin/codecept run functional
