language: php

sudo: false

php:
    - 5.6

services:
    - mysql

before_install:
    - mysql -e 'create database yii2_basic_tests; use mysql; update user set password=PASSWORD("root") where User="root";'

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - cd tests && php ./codeception/bin/yii migrate --interactive=0 && php ../vendor/bin/codecept run functional
