language: php

sudo: false

php:
    - 5.6

services:
    - mysql

before_script:
    - mysql -e "create database yii2_basic_tests; USE mysql;UPDATE user SET password=PASSWORD('root') WHERE user='root';FLUSH PRIVILEGES;"

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install --no-interaction --prefer-source

script:
    - cd tests && php ./codeception/bin/yii migrate --interactive=0 && php ../vendor/bin/codecept run functional
